apiVersion: apps/v1
kind: Deployment
metadata:
  name: starlette
  labels:
    app: starlette
spec:
  replicas: 3
  selector:
    matchLabels:
      app: starlette
  template:
    metadata:
      labels:
        app: starlette
    spec:
      containers:
      - name: starlette
        image: starlette:1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: starlette
spec:
  selector:
    app: starlette
  ports:
    - protocol: TCP
      port: 18000
      targetPort: 80
  type: LoadBalancer

